### ISSUE TITLE
Logo mozilla.cz není vertikálně vycentrované (v headbaru)

### ISSUE THREAD

**Issue by zelitomas** [MozillaCZ/firefox-cz#37]
![screenshot-2018-1-29 mozilla firefox - pripraven pro vas vase soukromi a otevreny web](https://user-images.githubusercontent.com/3105674/35489161-71cd590e-0493-11e8-8985-73f15267d928.png)

**Comment by MikkCZ** [comment]
@MekliCZ Mrkneš na to, jako CSS purista? Vzhledem k tomu, že vlastně používáme styl z Mozilla.org, je to tam stejné. Neopravíš to tedy přímo v https://github.com/mozilla/bedrock ? Pak nám bude stačit jenom aktualizovat, co odtamtud máme překopírované.

**Comment by MikkCZ** [comment]
Evidentně jsme to nikde nenahlásili do "upstreamu". Nahlášeno teď jako https://bugzilla.mozilla.org/show_bug.cgi?id=1488230

**Comment by MikkCZ** [comment]
Když tak na to koukám, toho záhlaví bychom se možná mohli úplně zbavit. Co myslíš @MekliCZ ? Nic v něm vlastně není.

**Comment by MikkCZ** [comment]
Bude vyřešeno s https://github.com/MozillaCZ/firefox-cz/issues/41
