### ISSUE TITLE
HTTPS pro Firefox.cz

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/firefox-cz#38]
Google začne výrazněji řvát o nezabezpečených webech a Firefox brzy také. Tomu bychom se měli s Firefox.cz vyhnout.

- [ ] převod domény
- [x] hosting s HTTPS místo GH pages (alias na ČH?, Netlify, https://jekyllrb.com/docs/deployment-methods/, ...)

**Comment by zelitomas** [comment]
Nebylo by snazší místo změny hostingu prostě před GitHub Pages postavit CloudFlare, který by zajišťoval HTTPS?

**Comment by MekliCZ** [comment]
CloudFlare jen přes moji mrtvolu. Můžem sdílet třeba certifikát s pornostránkou.Dne 9. 2. 2018 20:42 napsal uživatel Tomáš Zelina <notifications@github.com>:Nebylo by snazší místo změny hostingu prostě před GitHub Pages postavit CloudFlare, který by zajišťoval HTTPS?

**Comment by zelitomas** [comment]
To je pravda, na druhou sranu s CloudFlarem můžeme s HTTPS rovnou jednoduše zavést i DNSSEC (mají to vyloženě na pár klepnutí).

**Comment by MekliCZ** [comment]
Spíš by se mi líbilo Netlify. Funguje prakticky stejně jako GitHub Pages, akorát má Let's Encrypt a snadno se v něm nastavují hlavičky (abychom měli hezké skóre v Observatory).

**Comment by MikkCZ** [comment]
Pro začátek už mám Netlify připravené a poprosil jsem @JasnaPaka o nastavení DNS záznamů.

**Comment by MekliCZ** [comment]
@MikkCZ Nechtěli bychom tu doménu převést pod nás nebo Mozillu?

**Comment by MikkCZ** [comment]
Ano, měli bychom, pod Mozillu (viz první komentář ;) ). Měl jsem na to i v minulosti otevřený bug, ale nějak to usnulo. Psal jsem už o tom Pavlovi.

**Comment by MekliCZ** [comment]
Jo aha, já to špatně pochopil. :)

**Comment by MikkCZ** [comment]
Tak Firefox.cz už běží na Netlify, má HTTPS a zatím 1 den HSTS (později zvedneme na nějakou normální dobu). Povedlo se to i bez převodu domény. Ten řeším s Pavlem separátně a nemusíme kvůli němu nechávat tenhle ticket otevřený.
