### ISSUE TITLE
Loga Firefoxu na webu jsou černá

### ISSUE THREAD

**Issue by jrychly** [MozillaCZ/firefox-cz#39]
Loga firefoxu jsou černé a obrázky tam nejsou aktivní. Na webu to tak budí nepříjemný dojem. Chyba je v tom, že loga se načítají ze zdroje, který neexistuje. Zároveň se nezobrazuje ani favicon.
![obrazek](https://user-images.githubusercontent.com/18491023/37759700-a9d4cedc-2db4-11e8-9a9f-c955950fd784.png)

**Comment by zelitomas** [comment]
Na iPhonu to funguje:

![cb7263d4-fa43-44a0-95d1-42f6d817926e](https://user-images.githubusercontent.com/3105674/37773350-a8bcdb6a-2ddd-11e8-8d23-912388c0886f.png)

**Comment by jrychly** [comment]
Problém není u Safari. @MekliCZ to v Safari také funguje v pohodě, ale ve Firefoxu mu to nejde.

**Comment by MikkCZ** [comment]
Myslím, že by to mohlo souviset s nějakým post-processingem, který dělá Netlify (gzip nebo nějaké optimalizace). Podívám se na to.

**Comment by MikkCZ** [comment]
Hrál jsem si s nastavením, ale na nic jsem nepřišel. Poslal jsem tedy dotaz Netlify, co s tím obsahem po naklonování ještě dělají. I když je post-processing vypnutý, vidím o něm výpis v logu, ale to nemusí nutně znamenat, že se všechny kroky nakonec skutečně nepřeskočí.

**Comment by MikkCZ** [comment]
Mohlo za to CSP, které Firefox evidentně zohledňuje i pro SVG obrázky.
