### ISSUE TITLE
Vzhled podle Moz://a protocolu

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/firefox-cz#41]
viz https://protocol.mozilla.org/demos/index.html

**Comment by janbrasna** [comment]
Tady se na to pak taky vyhledove podivam, mozorg ma spousta protocol-ready layoutu s ruznymi landingpages, vc. uz predpripravenych barevnych "cakancu" reprezentujici jednotlive brandy, takze pak nekdy zkusim vykrast co uz je nekde upstream k dispozici, a mrknout zda z toho pujde neco smysluplne sestavit.
