### ISSUE TITLE
Další produkty "Firefox"

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/firefox-cz#44]
Mozilla rozšiřuje _brand_ Firefox na nové produkty. Měli bychom tedy přidat věci jako _Lockwise_, _Monitor_ atd.

**Comment by janbrasna** [comment]
A aktualne ten brand zase stahuje. Tzn. "FIrefox Browser" bude jen "Firerox", a "Firefox family of products" bude spis obecne "Mozilla family of products", mj. proto ze zas zacnou prezentovat napr. Thunderbird pod "svymi" produkty.

Nicmene ano, pujde ted o cca 9-10 produktu jako Monitor a VPN — je ale otazka zda je na tu .cz stranku pridavat, pokud vetsina nema lokalizaci. _(Jakmile bude nova produktova hierarchie nekde na staging, tak pak poslu link pro info, jak se to ted bude delit…)_
